# Generated by Django 4.1 on 2022-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Title", models.CharField(max_length=250)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
