# Generated by Django 4.1 on 2022-10-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="blog", old_name="Title", new_name="title",),
    ]
