# Generated by Django 4.1 on 2022-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_rename_title_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description",
            field=models.TextField(default="Empty Blog"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
